### ISSUE TITLE
Survminer package loading error

### ISSUE THREAD

**Issue by massimofagg** [kassambara/survminer#394]
Hello, 
I am encountering the following error when trying to load the survminer package:

Error: package or namespace load failed for ‘survminer’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘cmprsk’

Then I try to install the package cmprsk but unfortunately this package is not available for R version 3.5.1

How could I solve this?

Massimo

**Comment by massimofagg** [comment]
I solved by updating R to current version.

**Comment by kassambara** [comment]
so we can close this issue, thanks

**Comment by StevenMMortimer** [comment]
@kassambara I still believe this issue should be open as a bug and fixed because it implies your package documentation is not correct. Your package depends on R 3.6.0 because your dependencies (**cmprsk**) depend on R >= 3.6.0, but that's not defined in your `DESCRIPTION` file. I would recommend adding Depends: R (>= 3.6.0) to your `DESCRIPTION` file.

**Comment by kassambara** [comment]
Thank you @StevenMMortimer for pointing this out! We'll update the package accoordingly

**Comment by kassambara** [comment]
The recent update of package cmprsk suddenly requires the current R version >= 3.6.0, forcing survminer users to update their R version

As `cmprsk` is only used in documentations, we can move it from Imports section to suggests, so that the installation of survminer no longer needs cmprsk

**Comment by kassambara** [comment]
Dependency to cmprsk now removed.

You can install the latest dev version as follow:

```r
devtools::install_github("kassambara/survminer", build_vignettes = FALSE)
```
