### ISSUE TITLE
Question about ggcoxfunctional()

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#63]
Hi @MarcinKosinski,

I'm writing  series of blog posts on survival analyses using survminer for visualization part. Would you, please, clarify for me the two points below:  

1)
In the description section, it's stated that ggcoxfunctional() displays graphs of continuous explanatory variable against martingale residuals of **null** cox proportional hazards model [coxph(Surv(time, event)~1],  for each term.

However, in the R script, each continuous variable is plotted against the martingale residuals of a **univariate** cox model with the covariate [coxph(Surv(time, event)~explanatory.variable]

 **Is it OK? or should we change something in the description|R script.?**

2)
In all of examples I have seen, for assessing the nonlinearity of a continuous variable, people plot the continuous variable against the martingale residuals of the **whole** Cox model (Cox model with all covariates). This is not the case for ggcoxfunctional().  To be honest, the reason of this difference is not clear in my mind.  

**Could you, please clarify this for me?**

Thank you in advance,
Best,
/A

**Comment by MarcinKosinski** [comment]
Thank for pointing this out.

Talking about 1) it should be  `resid(coxph(Surv(time, event)~1))  ~ f(explanatory.variable)` so the plot should present transformation of 1 variable against the martingale residuals of the null model.

*This is my mistake and should be fixed*.

2) Talking about this part. Can you provide those examples that have you seen? I have seen all examples with null model :) If one would like to test the functional form for the variable `X1` against the whole model, then imagine the situation that you have *2* continuous variables: `X1` and `X2` and many categorical variables `Y1, Y2,. ... YN`.

For `X1` would you check residuals of which `whole` model?
 
- `resid(coxph(Surv(time, event)~Y1+Y2+...YN+f_1(X2))  ~ f_1(X1)`
- `resid(coxph(Surv(time, event)~Y1+Y2+...YN+f_2(X2))  ~ f_1(X1)`
- `resid(coxph(Surv(time, event)~Y1+Y2+...YN+f_3(X2))  ~ f_1(X1)`
- ...
- `resid(coxph(Surv(time, event)~Y1+Y2+...YN+f_infty(X2))  ~ f_1(X1)`

? And there are milion of possible models to check agains for only one `f_1` transformation fo `X1`.
So checking against null model is rather more natural because there is only 1 possible model. I can not come out with more scientific justification as I don't actually remember the martingale theory in the survival cox ph models right now

**Comment by MarcinKosinski** [comment]
Could you please add links to those blog posts to the survminer README.md file : ) ?

**Comment by kassambara** [comment]
Thank you for this very clear explanation and I'll add the link to the blog posts
for 1,) I changed the ggcoxfunctional() R script accordingly.
for 2), your explanation confirms what I was thinking  also, so I definitively agree with you.

Have a great day!!!!
